#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : messagelib
Version  : 20.04.2
Release  : 27
URL      : https://download.kde.org/stable/release-service/20.04.2/src/messagelib-20.04.2.tar.xz
Source0  : https://download.kde.org/stable/release-service/20.04.2/src/messagelib-20.04.2.tar.xz
Source1  : https://download.kde.org/stable/release-service/20.04.2/src/messagelib-20.04.2.tar.xz.sig
Summary  : KDE PIM messaging library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: messagelib-data = %{version}-%{release}
Requires: messagelib-lib = %{version}-%{release}
Requires: messagelib-license = %{version}-%{release}
Requires: messagelib-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : akonadi-search-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : git
BuildRequires : gpgme-dev
BuildRequires : grantlee-dev
BuildRequires : grantleetheme-dev
BuildRequires : karchive-dev
BuildRequires : kcalendarcore-dev
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfig-dev
BuildRequires : kconfigwidgets-dev
BuildRequires : kcontacts-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdepim-apps-libs-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kimap-dev
BuildRequires : kio-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : kldap-dev
BuildRequires : kmailtransport-dev
BuildRequires : kmbox-dev
BuildRequires : kmime-dev
BuildRequires : knewstuff-dev
BuildRequires : kpimtextedit-dev
BuildRequires : kservice-dev
BuildRequires : ktextwidgets-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kxmlgui-dev
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libgravatar-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : pimcommon-dev
BuildRequires : qca-qt5-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtwebengine-dev
BuildRequires : sonnet-dev
BuildRequires : syntax-highlighting-dev

%description
What should be put here?
========================
Stuff here needs to comply with at least these rules (additionally to all the other ones that apply to all code):
- no dependencies on legacy libs (libkdepim)
- no dependencies on:
- libmessagelist
- libmessageviewer
- libmessagecomposer
- used by at least one of the above listed libs
- used by at least one other component (most commonly a second one of the above listed libs)

%package data
Summary: data components for the messagelib package.
Group: Data

%description data
data components for the messagelib package.


%package dev
Summary: dev components for the messagelib package.
Group: Development
Requires: messagelib-lib = %{version}-%{release}
Requires: messagelib-data = %{version}-%{release}
Provides: messagelib-devel = %{version}-%{release}
Requires: messagelib = %{version}-%{release}

%description dev
dev components for the messagelib package.


%package lib
Summary: lib components for the messagelib package.
Group: Libraries
Requires: messagelib-data = %{version}-%{release}
Requires: messagelib-license = %{version}-%{release}

%description lib
lib components for the messagelib package.


%package license
Summary: license components for the messagelib package.
Group: Default

%description license
license components for the messagelib package.


%package locales
Summary: locales components for the messagelib package.
Group: Default

%description locales
locales components for the messagelib package.


%prep
%setup -q -n messagelib-20.04.2
cd %{_builddir}/messagelib-20.04.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591933369
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1591933369
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/messagelib
cp %{_builddir}/messagelib-20.04.2/COPYING %{buildroot}/usr/share/package-licenses/messagelib/6a3bf83ab62e047649bdf91a17c9311737cede0f
cp %{_builddir}/messagelib-20.04.2/COPYING.LIB %{buildroot}/usr/share/package-licenses/messagelib/c914b1f9fc73a1ae187da32447bd161823f8b9e8
pushd clr-build
%make_install
popd
%find_lang libmessagecomposer
%find_lang libmessagecore
%find_lang libmessagelist
%find_lang libmessageviewer
%find_lang libmimetreeparser
%find_lang libtemplateparser
%find_lang libwebengineviewer

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/config.kcfg/customtemplates_kfg.kcfg
/usr/share/config.kcfg/templatesconfiguration_kfg.kcfg
/usr/share/kconf_update/messageviewer.upd
/usr/share/knotifications5/messageviewer.notifyrc
/usr/share/knsrcfiles/messageviewer_header_themes.knsrc
/usr/share/libmessageviewer/pics/enterprise_bottom.png
/usr/share/libmessageviewer/pics/enterprise_bottom_left.png
/usr/share/libmessageviewer/pics/enterprise_bottom_right.png
/usr/share/libmessageviewer/pics/enterprise_icon.png
/usr/share/libmessageviewer/pics/enterprise_left.png
/usr/share/libmessageviewer/pics/enterprise_right.png
/usr/share/libmessageviewer/pics/enterprise_s_left.png
/usr/share/libmessageviewer/pics/enterprise_s_right.png
/usr/share/libmessageviewer/pics/enterprise_sbar.png
/usr/share/libmessageviewer/pics/enterprise_sp_right.png
/usr/share/libmessageviewer/pics/enterprise_sw.png
/usr/share/libmessageviewer/pics/enterprise_top.png
/usr/share/libmessageviewer/pics/enterprise_top_left.png
/usr/share/libmessageviewer/pics/enterprise_top_right.png
/usr/share/libmessageviewer/pics/enterprise_w.png
/usr/share/libmessageviewer/pics/quicklistClosed.png
/usr/share/libmessageviewer/pics/quicklistOpened.png
/usr/share/libmessageviewer/pics/quotecollapse.png
/usr/share/libmessageviewer/pics/quoteexpand.png
/usr/share/messagelist/pics/mail-horizontal-space.png
/usr/share/messagelist/pics/mail-vertical-separator-line.png
/usr/share/messageviewer/about/default/background.png
/usr/share/messageviewer/about/default/main.css
/usr/share/messageviewer/about/default/main.html
/usr/share/messageviewer/about/default/splash.theme
/usr/share/messageviewer/about/default/status.html
/usr/share/messageviewer/defaultthemes/5.2/header.html
/usr/share/messageviewer/defaultthemes/5.2/kmail_default.desktop
/usr/share/messageviewer/defaultthemes/5.2/photo.png
/usr/share/messageviewer/defaultthemes/5.2/photo.svg
/usr/share/messageviewer/defaultthemes/5.2/style.css
/usr/share/messageviewer/longurlServices.json
/usr/share/org.kde.syntax-highlighting/syntax/kmail-template.xml
/usr/share/qlogging-categories5/messagelib.categories
/usr/share/qlogging-categories5/messagelib.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/MessageComposer/AbstractEncryptJob
/usr/include/KF5/MessageComposer/AkonadiSender
/usr/include/KF5/MessageComposer/AliasesExpandJob
/usr/include/KF5/MessageComposer/AttachmentClipBoardJob
/usr/include/KF5/MessageComposer/AttachmentControllerBase
/usr/include/KF5/MessageComposer/AttachmentFromPublicKeyJob
/usr/include/KF5/MessageComposer/AttachmentJob
/usr/include/KF5/MessageComposer/AttachmentModel
/usr/include/KF5/MessageComposer/AttachmentVcardFromAddressBookJob
/usr/include/KF5/MessageComposer/Composer
/usr/include/KF5/MessageComposer/ComposerAttachmentInterface
/usr/include/KF5/MessageComposer/ComposerLineEdit
/usr/include/KF5/MessageComposer/ComposerViewBase
/usr/include/KF5/MessageComposer/ComposerViewInterface
/usr/include/KF5/MessageComposer/ContentJobBase
/usr/include/KF5/MessageComposer/ConvertSnippetVariableMenu
/usr/include/KF5/MessageComposer/ConvertSnippetVariablesJob
/usr/include/KF5/MessageComposer/ConvertSnippetVariablesUtil
/usr/include/KF5/MessageComposer/EncryptJob
/usr/include/KF5/MessageComposer/FollowUpReminderSelectDateDialog
/usr/include/KF5/MessageComposer/FollowupReminderCreateJob
/usr/include/KF5/MessageComposer/GlobalPart
/usr/include/KF5/MessageComposer/ImageScalingWidget
/usr/include/KF5/MessageComposer/InfoPart
/usr/include/KF5/MessageComposer/InsertTextFileJob
/usr/include/KF5/MessageComposer/JobBase
/usr/include/KF5/MessageComposer/Kleo_Util
/usr/include/KF5/MessageComposer/MainTextJob
/usr/include/KF5/MessageComposer/MessageComposerSettings
/usr/include/KF5/MessageComposer/MessageFactoryNG
/usr/include/KF5/MessageComposer/MessageHelper
/usr/include/KF5/MessageComposer/MessagePart
/usr/include/KF5/MessageComposer/MessageSender
/usr/include/KF5/MessageComposer/MultipartJob
/usr/include/KF5/MessageComposer/PluginActionType
/usr/include/KF5/MessageComposer/PluginComposerInterface
/usr/include/KF5/MessageComposer/PluginEditor
/usr/include/KF5/MessageComposer/PluginEditorCheckBeforeSend
/usr/include/KF5/MessageComposer/PluginEditorCheckBeforeSendConfigureWidget
/usr/include/KF5/MessageComposer/PluginEditorCheckBeforeSendInterface
/usr/include/KF5/MessageComposer/PluginEditorCheckBeforeSendManager
/usr/include/KF5/MessageComposer/PluginEditorCheckBeforeSendParams
/usr/include/KF5/MessageComposer/PluginEditorConvertText
/usr/include/KF5/MessageComposer/PluginEditorConvertTextConfigureWidget
/usr/include/KF5/MessageComposer/PluginEditorConvertTextInterface
/usr/include/KF5/MessageComposer/PluginEditorConvertTextManager
/usr/include/KF5/MessageComposer/PluginEditorConverterBeforeConvertingData
/usr/include/KF5/MessageComposer/PluginEditorConverterInitialData
/usr/include/KF5/MessageComposer/PluginEditorGrammarCustomToolsViewInterface
/usr/include/KF5/MessageComposer/PluginEditorGrammarManager
/usr/include/KF5/MessageComposer/PluginEditorInit
/usr/include/KF5/MessageComposer/PluginEditorInitConfigureWidget
/usr/include/KF5/MessageComposer/PluginEditorInitInterface
/usr/include/KF5/MessageComposer/PluginEditorInitManager
/usr/include/KF5/MessageComposer/PluginEditorInterface
/usr/include/KF5/MessageComposer/PluginEditorManager
/usr/include/KF5/MessageComposer/Recipient
/usr/include/KF5/MessageComposer/RecipientLine
/usr/include/KF5/MessageComposer/RecipientsEditor
/usr/include/KF5/MessageComposer/RichTextComposerNg
/usr/include/KF5/MessageComposer/RichTextComposerSignatures
/usr/include/KF5/MessageComposer/SignJob
/usr/include/KF5/MessageComposer/SignatureController
/usr/include/KF5/MessageComposer/SinglepartJob
/usr/include/KF5/MessageComposer/SkeletonMessageJob
/usr/include/KF5/MessageComposer/StatusBarLabelToggledState
/usr/include/KF5/MessageComposer/TextPart
/usr/include/KF5/MessageComposer/TransparentJob
/usr/include/KF5/MessageComposer/Util
/usr/include/KF5/MessageCore/AttachmentCompressJob
/usr/include/KF5/MessageCore/AttachmentFromUrlBaseJob
/usr/include/KF5/MessageCore/AttachmentFromUrlUtils
/usr/include/KF5/MessageCore/AttachmentLoadJob
/usr/include/KF5/MessageCore/AttachmentPart
/usr/include/KF5/MessageCore/AttachmentPropertiesDialog
/usr/include/KF5/MessageCore/AttachmentUpdateJob
/usr/include/KF5/MessageCore/ImageCollector
/usr/include/KF5/MessageCore/MailingList
/usr/include/KF5/MessageCore/MessageCoreSettings
/usr/include/KF5/MessageCore/MessageCoreUtil
/usr/include/KF5/MessageCore/NodeHelper
/usr/include/KF5/MessageCore/StringUtil
/usr/include/KF5/MessageList/AggregationComboBox
/usr/include/KF5/MessageList/AggregationConfigButton
/usr/include/KF5/MessageList/Enums
/usr/include/KF5/MessageList/MessageListUtil
/usr/include/KF5/MessageList/Pane
/usr/include/KF5/MessageList/QuickSearchLine
/usr/include/KF5/MessageList/StorageModel
/usr/include/KF5/MessageList/StorageModelBase
/usr/include/KF5/MessageList/ThemeComboBox
/usr/include/KF5/MessageList/ThemeConfigButton
/usr/include/KF5/MessageList/View
/usr/include/KF5/MessageList/WidgetBase
/usr/include/KF5/MessageViewer/AttachmentStrategy
/usr/include/KF5/MessageViewer/BlockMailTrackingUrlInterceptor
/usr/include/KF5/MessageViewer/BodyPartURLHandler
/usr/include/KF5/MessageViewer/BufferedHtmlWriter
/usr/include/KF5/MessageViewer/CSSHelper
/usr/include/KF5/MessageViewer/CSSHelperBase
/usr/include/KF5/MessageViewer/ConfigureWidget
/usr/include/KF5/MessageViewer/DKIMCheckPolicy
/usr/include/KF5/MessageViewer/DKIMCheckSignatureJob
/usr/include/KF5/MessageViewer/DKIMHeaderParser
/usr/include/KF5/MessageViewer/DKIMInfo
/usr/include/KF5/MessageViewer/DKIMKeyRecord
/usr/include/KF5/MessageViewer/DKIMManageRulesDialog
/usr/include/KF5/MessageViewer/DKIMManageRulesWidget
/usr/include/KF5/MessageViewer/DKIMManager
/usr/include/KF5/MessageViewer/DKIMManagerAuthenticationServer
/usr/include/KF5/MessageViewer/DKIMManagerKey
/usr/include/KF5/MessageViewer/DKIMManagerKeyDialog
/usr/include/KF5/MessageViewer/DKIMManagerKeyWidget
/usr/include/KF5/MessageViewer/DKIMManagerRules
/usr/include/KF5/MessageViewer/DKIMRule
/usr/include/KF5/MessageViewer/DKIMViewerMenu
/usr/include/KF5/MessageViewer/DKIMWidgetInfo
/usr/include/KF5/MessageViewer/EditorWatcher
/usr/include/KF5/MessageViewer/FileHtmlWriter
/usr/include/KF5/MessageViewer/GrantleeHeaderStyle
/usr/include/KF5/MessageViewer/GrantleeHeaderTestStyle
/usr/include/KF5/MessageViewer/HeaderStrategy
/usr/include/KF5/MessageViewer/HeaderStyle
/usr/include/KF5/MessageViewer/HeaderStyleInterface
/usr/include/KF5/MessageViewer/HeaderStyleMenuManager
/usr/include/KF5/MessageViewer/HeaderStylePlugin
/usr/include/KF5/MessageViewer/HeaderStylePluginManager
/usr/include/KF5/MessageViewer/HeaderStyle_Util
/usr/include/KF5/MessageViewer/HtmlBlock
/usr/include/KF5/MessageViewer/HtmlWriter
/usr/include/KF5/MessageViewer/IconNameCache
/usr/include/KF5/MessageViewer/InvitationSettings
/usr/include/KF5/MessageViewer/KXFace
/usr/include/KF5/MessageViewer/MailWebEnginePage
/usr/include/KF5/MessageViewer/MailWebEngineView
/usr/include/KF5/MessageViewer/MarkMessageReadHandler
/usr/include/KF5/MessageViewer/MessagePartRenderPlugin
/usr/include/KF5/MessageViewer/MessagePartRendererBase
/usr/include/KF5/MessageViewer/MessagePartRendererManager
/usr/include/KF5/MessageViewer/MessageViewerConfigureSettingsPlugin
/usr/include/KF5/MessageViewer/MessageViewerConfigureSettingsPluginManager
/usr/include/KF5/MessageViewer/MessageViewerConfigureSettingsPluginWidget
/usr/include/KF5/MessageViewer/MessageViewerSettings
/usr/include/KF5/MessageViewer/MessageViewerUtil
/usr/include/KF5/MessageViewer/MimeType
/usr/include/KF5/MessageViewer/ObjectTreeEmptySource
/usr/include/KF5/MessageViewer/PlainHeaderStyle
/usr/include/KF5/MessageViewer/PrintingSettings
/usr/include/KF5/MessageViewer/RichHeaderStrategy
/usr/include/KF5/MessageViewer/ScamCheckShortUrl
/usr/include/KF5/MessageViewer/ScamCheckShortUrlManager
/usr/include/KF5/MessageViewer/ScamExpandUrlJob
/usr/include/KF5/MessageViewer/SpamHeaderAnalyzer
/usr/include/KF5/MessageViewer/Stl_Util
/usr/include/KF5/MessageViewer/URLHandler
/usr/include/KF5/MessageViewer/Viewer
/usr/include/KF5/MessageViewer/ViewerPlugin
/usr/include/KF5/MessageViewer/ViewerPluginInterface
/usr/include/KF5/MessageViewer/ViewerPluginManager
/usr/include/KF5/MessageViewer/ViewerPluginToolManager
/usr/include/KF5/MimeTreeParser/AttachmentTemporaryFilesDirs
/usr/include/KF5/MimeTreeParser/BodyPart
/usr/include/KF5/MimeTreeParser/BodyPartFormatter
/usr/include/KF5/MimeTreeParser/BodyPartFormatterFactory
/usr/include/KF5/MimeTreeParser/Enums
/usr/include/KF5/MimeTreeParser/MessagePart
/usr/include/KF5/MimeTreeParser/NodeHelper
/usr/include/KF5/MimeTreeParser/ObjectTreeParser
/usr/include/KF5/MimeTreeParser/ObjectTreeSource
/usr/include/KF5/MimeTreeParser/PartMetaData
/usr/include/KF5/MimeTreeParser/PartNodeBodyPart
/usr/include/KF5/MimeTreeParser/SimpleObjectTreeSource
/usr/include/KF5/MimeTreeParser/Util
/usr/include/KF5/TemplateParser/CustomTemplates
/usr/include/KF5/TemplateParser/CustomTemplatesMenu
/usr/include/KF5/TemplateParser/DefaultTemplates
/usr/include/KF5/TemplateParser/TemplateConvertCommandJob
/usr/include/KF5/TemplateParser/TemplateParserEmailAddressRequesterBase
/usr/include/KF5/TemplateParser/TemplateParserExtractHtmlInfoResult
/usr/include/KF5/TemplateParser/TemplateParserJob
/usr/include/KF5/TemplateParser/TemplatesCommandMenu
/usr/include/KF5/TemplateParser/TemplatesConfiguration
/usr/include/KF5/TemplateParser/TemplatesInsertCommandAction
/usr/include/KF5/TemplateParser/TemplatesInsertCommandPushButton
/usr/include/KF5/TemplateParser/TemplatesTextEdit
/usr/include/KF5/TemplateParser/TemplatesUtil
/usr/include/KF5/WebEngineViewer/CheckPhishingUrlCache
/usr/include/KF5/WebEngineViewer/CheckPhishingUrlJob
/usr/include/KF5/WebEngineViewer/CheckPhishingUrlUtil
/usr/include/KF5/WebEngineViewer/CreatePhishingUrlDataBaseJob
/usr/include/KF5/WebEngineViewer/FindBarBase
/usr/include/KF5/WebEngineViewer/FindBarWebEngineView
/usr/include/KF5/WebEngineViewer/HashCacheManager
/usr/include/KF5/WebEngineViewer/InterceptorManager
/usr/include/KF5/WebEngineViewer/LocalDataBaseManager
/usr/include/KF5/WebEngineViewer/NetworkPluginUrlInterceptor
/usr/include/KF5/WebEngineViewer/NetworkPluginUrlInterceptorConfigureWidget
/usr/include/KF5/WebEngineViewer/NetworkPluginUrlInterceptorInterface
/usr/include/KF5/WebEngineViewer/NetworkUrlInterceptor
/usr/include/KF5/WebEngineViewer/NetworkUrlInterceptorPluginManager
/usr/include/KF5/WebEngineViewer/SearchFullHashJob
/usr/include/KF5/WebEngineViewer/UpdateDataBaseInfo
/usr/include/KF5/WebEngineViewer/WebEngineAccessKey
/usr/include/KF5/WebEngineViewer/WebEngineExportHtmlPageJob
/usr/include/KF5/WebEngineViewer/WebEngineExportPdfPageJob
/usr/include/KF5/WebEngineViewer/WebEngineManageScript
/usr/include/KF5/WebEngineViewer/WebEnginePage
/usr/include/KF5/WebEngineViewer/WebEngineScript
/usr/include/KF5/WebEngineViewer/WebEngineView
/usr/include/KF5/WebEngineViewer/WebHitTest
/usr/include/KF5/WebEngineViewer/WebHitTestResult
/usr/include/KF5/WebEngineViewer/ZoomActionMenu
/usr/include/KF5/messagecomposer/abstractencryptjob.h
/usr/include/KF5/messagecomposer/akonadisender.h
/usr/include/KF5/messagecomposer/aliasesexpandjob.h
/usr/include/KF5/messagecomposer/attachmentclipboardjob.h
/usr/include/KF5/messagecomposer/attachmentcontrollerbase.h
/usr/include/KF5/messagecomposer/attachmentfrompublickeyjob.h
/usr/include/KF5/messagecomposer/attachmentjob.h
/usr/include/KF5/messagecomposer/attachmentmodel.h
/usr/include/KF5/messagecomposer/attachmentvcardfromaddressbookjob.h
/usr/include/KF5/messagecomposer/composer.h
/usr/include/KF5/messagecomposer/composerattachmentinterface.h
/usr/include/KF5/messagecomposer/composerlineedit.h
/usr/include/KF5/messagecomposer/composerviewbase.h
/usr/include/KF5/messagecomposer/composerviewinterface.h
/usr/include/KF5/messagecomposer/contentjobbase.h
/usr/include/KF5/messagecomposer/convertsnippetvariablemenu.h
/usr/include/KF5/messagecomposer/convertsnippetvariablesjob.h
/usr/include/KF5/messagecomposer/convertsnippetvariablesutil.h
/usr/include/KF5/messagecomposer/encryptjob.h
/usr/include/KF5/messagecomposer/followupremindercreatejob.h
/usr/include/KF5/messagecomposer/followupreminderselectdatedialog.h
/usr/include/KF5/messagecomposer/globalpart.h
/usr/include/KF5/messagecomposer/imagescalingwidget.h
/usr/include/KF5/messagecomposer/infopart.h
/usr/include/KF5/messagecomposer/inserttextfilejob.h
/usr/include/KF5/messagecomposer/jobbase.h
/usr/include/KF5/messagecomposer/kleo_util.h
/usr/include/KF5/messagecomposer/maintextjob.h
/usr/include/KF5/messagecomposer/messagecomposer_debug.h
/usr/include/KF5/messagecomposer/messagecomposer_export.h
/usr/include/KF5/messagecomposer/messagecomposersettings.h
/usr/include/KF5/messagecomposer/messagecomposersettings_base.h
/usr/include/KF5/messagecomposer/messagefactoryng.h
/usr/include/KF5/messagecomposer/messagehelper.h
/usr/include/KF5/messagecomposer/messagepart.h
/usr/include/KF5/messagecomposer/messagesender.h
/usr/include/KF5/messagecomposer/multipartjob.h
/usr/include/KF5/messagecomposer/pluginactiontype.h
/usr/include/KF5/messagecomposer/plugincomposerinterface.h
/usr/include/KF5/messagecomposer/plugineditor.h
/usr/include/KF5/messagecomposer/plugineditorcheckbeforesend.h
/usr/include/KF5/messagecomposer/plugineditorcheckbeforesendconfigurewidget.h
/usr/include/KF5/messagecomposer/plugineditorcheckbeforesendinterface.h
/usr/include/KF5/messagecomposer/plugineditorcheckbeforesendmanager.h
/usr/include/KF5/messagecomposer/plugineditorcheckbeforesendparams.h
/usr/include/KF5/messagecomposer/plugineditorconverterbeforeconvertingdata.h
/usr/include/KF5/messagecomposer/plugineditorconverterinitialdata.h
/usr/include/KF5/messagecomposer/plugineditorconverttext.h
/usr/include/KF5/messagecomposer/plugineditorconverttextconfigurewidget.h
/usr/include/KF5/messagecomposer/plugineditorconverttextinterface.h
/usr/include/KF5/messagecomposer/plugineditorconverttextmanager.h
/usr/include/KF5/messagecomposer/plugineditorgrammarcustomtoolsviewinterface.h
/usr/include/KF5/messagecomposer/plugineditorgrammarmanager.h
/usr/include/KF5/messagecomposer/plugineditorinit.h
/usr/include/KF5/messagecomposer/plugineditorinitconfigurewidget.h
/usr/include/KF5/messagecomposer/plugineditorinitinterface.h
/usr/include/KF5/messagecomposer/plugineditorinitmanager.h
/usr/include/KF5/messagecomposer/plugineditorinterface.h
/usr/include/KF5/messagecomposer/plugineditormanager.h
/usr/include/KF5/messagecomposer/recipient.h
/usr/include/KF5/messagecomposer/recipientline.h
/usr/include/KF5/messagecomposer/recipientseditor.h
/usr/include/KF5/messagecomposer/richtextcomposerng.h
/usr/include/KF5/messagecomposer/richtextcomposersignatures.h
/usr/include/KF5/messagecomposer/signaturecontroller.h
/usr/include/KF5/messagecomposer/signjob.h
/usr/include/KF5/messagecomposer/singlepartjob.h
/usr/include/KF5/messagecomposer/skeletonmessagejob.h
/usr/include/KF5/messagecomposer/statusbarlabeltoggledstate.h
/usr/include/KF5/messagecomposer/textpart.h
/usr/include/KF5/messagecomposer/transparentjob.h
/usr/include/KF5/messagecomposer/util.h
/usr/include/KF5/messagecomposer_version.h
/usr/include/KF5/messagecore/attachmentcompressjob.h
/usr/include/KF5/messagecore/attachmentfromurlbasejob.h
/usr/include/KF5/messagecore/attachmentfromurlutils.h
/usr/include/KF5/messagecore/attachmentloadjob.h
/usr/include/KF5/messagecore/attachmentpart.h
/usr/include/KF5/messagecore/attachmentpropertiesdialog.h
/usr/include/KF5/messagecore/attachmentupdatejob.h
/usr/include/KF5/messagecore/globalsettings_messagecore.h
/usr/include/KF5/messagecore/imagecollector.h
/usr/include/KF5/messagecore/mailinglist.h
/usr/include/KF5/messagecore/messagecore_export.h
/usr/include/KF5/messagecore/messagecoresettings.h
/usr/include/KF5/messagecore/messagecoreutil.h
/usr/include/KF5/messagecore/nodehelper.h
/usr/include/KF5/messagecore/stringutil.h
/usr/include/KF5/messagecore_version.h
/usr/include/KF5/messagelist/aggregationcombobox.h
/usr/include/KF5/messagelist/aggregationconfigbutton.h
/usr/include/KF5/messagelist/enums.h
/usr/include/KF5/messagelist/messagelist_export.h
/usr/include/KF5/messagelist/messagelistsettings.h
/usr/include/KF5/messagelist/messagelistutil.h
/usr/include/KF5/messagelist/pane.h
/usr/include/KF5/messagelist/quicksearchline.h
/usr/include/KF5/messagelist/storagemodel.h
/usr/include/KF5/messagelist/storagemodelbase.h
/usr/include/KF5/messagelist/themecombobox.h
/usr/include/KF5/messagelist/themeconfigbutton.h
/usr/include/KF5/messagelist/view.h
/usr/include/KF5/messagelist/widgetbase.h
/usr/include/KF5/messagelist_version.h
/usr/include/KF5/messageviewer/attachmentstrategy.h
/usr/include/KF5/messageviewer/blockmailtrackingurlinterceptor.h
/usr/include/KF5/messageviewer/bodyparturlhandler.h
/usr/include/KF5/messageviewer/bufferedhtmlwriter.h
/usr/include/KF5/messageviewer/config-messageviewer.h
/usr/include/KF5/messageviewer/configurewidget.h
/usr/include/KF5/messageviewer/csshelper.h
/usr/include/KF5/messageviewer/csshelperbase.h
/usr/include/KF5/messageviewer/dkimcheckpolicy.h
/usr/include/KF5/messageviewer/dkimchecksignaturejob.h
/usr/include/KF5/messageviewer/dkimheaderparser.h
/usr/include/KF5/messageviewer/dkiminfo.h
/usr/include/KF5/messageviewer/dkimkeyrecord.h
/usr/include/KF5/messageviewer/dkimmanager.h
/usr/include/KF5/messageviewer/dkimmanagerauthenticationserver.h
/usr/include/KF5/messageviewer/dkimmanagerkey.h
/usr/include/KF5/messageviewer/dkimmanagerkeydialog.h
/usr/include/KF5/messageviewer/dkimmanagerkeywidget.h
/usr/include/KF5/messageviewer/dkimmanagerrules.h
/usr/include/KF5/messageviewer/dkimmanagerulesdialog.h
/usr/include/KF5/messageviewer/dkimmanageruleswidget.h
/usr/include/KF5/messageviewer/dkimrule.h
/usr/include/KF5/messageviewer/dkimviewermenu.h
/usr/include/KF5/messageviewer/dkimwidgetinfo.h
/usr/include/KF5/messageviewer/editorwatcher.h
/usr/include/KF5/messageviewer/filehtmlwriter.h
/usr/include/KF5/messageviewer/globalsettings_messageviewer.h
/usr/include/KF5/messageviewer/grantleeheaderstyle.h
/usr/include/KF5/messageviewer/grantleeheaderteststyle.h
/usr/include/KF5/messageviewer/headerstrategy.h
/usr/include/KF5/messageviewer/headerstyle.h
/usr/include/KF5/messageviewer/headerstyle_util.h
/usr/include/KF5/messageviewer/headerstyleinterface.h
/usr/include/KF5/messageviewer/headerstylemenumanager.h
/usr/include/KF5/messageviewer/headerstyleplugin.h
/usr/include/KF5/messageviewer/headerstylepluginmanager.h
/usr/include/KF5/messageviewer/htmlblock.h
/usr/include/KF5/messageviewer/htmlwriter.h
/usr/include/KF5/messageviewer/iconnamecache.h
/usr/include/KF5/messageviewer/invitationsettings.h
/usr/include/KF5/messageviewer/kxface.h
/usr/include/KF5/messageviewer/mailwebenginepage.h
/usr/include/KF5/messageviewer/mailwebengineview.h
/usr/include/KF5/messageviewer/markmessagereadhandler.h
/usr/include/KF5/messageviewer/messagepartrendererbase.h
/usr/include/KF5/messageviewer/messagepartrenderermanager.h
/usr/include/KF5/messageviewer/messagepartrenderplugin.h
/usr/include/KF5/messageviewer/messageviewer_debug.h
/usr/include/KF5/messageviewer/messageviewer_export.h
/usr/include/KF5/messageviewer/messageviewerconfiguresettingsplugin.h
/usr/include/KF5/messageviewer/messageviewerconfiguresettingspluginmanager.h
/usr/include/KF5/messageviewer/messageviewerconfiguresettingspluginwidget.h
/usr/include/KF5/messageviewer/messageviewersettings.h
/usr/include/KF5/messageviewer/messageviewerutil.h
/usr/include/KF5/messageviewer/mimetype.h
/usr/include/KF5/messageviewer/objecttreeemptysource.h
/usr/include/KF5/messageviewer/plainheaderstyle.h
/usr/include/KF5/messageviewer/printingsettings.h
/usr/include/KF5/messageviewer/richheaderstrategy.h
/usr/include/KF5/messageviewer/scamcheckshorturl.h
/usr/include/KF5/messageviewer/scamcheckshorturlmanager.h
/usr/include/KF5/messageviewer/scamexpandurljob.h
/usr/include/KF5/messageviewer/spamheaderanalyzer.h
/usr/include/KF5/messageviewer/stl_util.h
/usr/include/KF5/messageviewer/urlhandler.h
/usr/include/KF5/messageviewer/viewer.h
/usr/include/KF5/messageviewer/viewerplugin.h
/usr/include/KF5/messageviewer/viewerplugininterface.h
/usr/include/KF5/messageviewer/viewerpluginmanager.h
/usr/include/KF5/messageviewer/viewerplugintoolmanager.h
/usr/include/KF5/messageviewer_version.h
/usr/include/KF5/mimetreeparser/attachmenttemporaryfilesdirs.h
/usr/include/KF5/mimetreeparser/bodypart.h
/usr/include/KF5/mimetreeparser/bodypartformatter.h
/usr/include/KF5/mimetreeparser/bodypartformatterfactory.h
/usr/include/KF5/mimetreeparser/enums.h
/usr/include/KF5/mimetreeparser/messagepart.h
/usr/include/KF5/mimetreeparser/mimetreeparser_export.h
/usr/include/KF5/mimetreeparser/nodehelper.h
/usr/include/KF5/mimetreeparser/objecttreeparser.h
/usr/include/KF5/mimetreeparser/objecttreesource.h
/usr/include/KF5/mimetreeparser/partmetadata.h
/usr/include/KF5/mimetreeparser/partnodebodypart.h
/usr/include/KF5/mimetreeparser/simpleobjecttreesource.h
/usr/include/KF5/mimetreeparser/util.h
/usr/include/KF5/mimetreeparser_version.h
/usr/include/KF5/templateparser/customtemplates.h
/usr/include/KF5/templateparser/customtemplates_kfg.h
/usr/include/KF5/templateparser/customtemplatesmenu.h
/usr/include/KF5/templateparser/defaulttemplates.h
/usr/include/KF5/templateparser/globalsettings_templateparser.h
/usr/include/KF5/templateparser/templateconvertcommandjob.h
/usr/include/KF5/templateparser/templateparser_export.h
/usr/include/KF5/templateparser/templateparseremailaddressrequesterbase.h
/usr/include/KF5/templateparser/templateparserextracthtmlinforesult.h
/usr/include/KF5/templateparser/templateparserjob.h
/usr/include/KF5/templateparser/templatescommandmenu.h
/usr/include/KF5/templateparser/templatesconfiguration.h
/usr/include/KF5/templateparser/templatesconfiguration_kfg.h
/usr/include/KF5/templateparser/templatesinsertcommandaction.h
/usr/include/KF5/templateparser/templatesinsertcommandpushbutton.h
/usr/include/KF5/templateparser/templatestextedit.h
/usr/include/KF5/templateparser/templatesutil.h
/usr/include/KF5/templateparser/ui_templatesconfiguration_base.h
/usr/include/KF5/templateparser_version.h
/usr/include/KF5/webengineviewer/checkphishingurlcache.h
/usr/include/KF5/webengineviewer/checkphishingurljob.h
/usr/include/KF5/webengineviewer/checkphishingurlutil.h
/usr/include/KF5/webengineviewer/createphishingurldatabasejob.h
/usr/include/KF5/webengineviewer/findbarbase.h
/usr/include/KF5/webengineviewer/findbarwebengineview.h
/usr/include/KF5/webengineviewer/hashcachemanager.h
/usr/include/KF5/webengineviewer/interceptormanager.h
/usr/include/KF5/webengineviewer/localdatabasemanager.h
/usr/include/KF5/webengineviewer/networkpluginurlinterceptor.h
/usr/include/KF5/webengineviewer/networkpluginurlinterceptorconfigurewidget.h
/usr/include/KF5/webengineviewer/networkpluginurlinterceptorinterface.h
/usr/include/KF5/webengineviewer/networkurlinterceptor.h
/usr/include/KF5/webengineviewer/networkurlinterceptorpluginmanager.h
/usr/include/KF5/webengineviewer/searchfullhashjob.h
/usr/include/KF5/webengineviewer/updatedatabaseinfo.h
/usr/include/KF5/webengineviewer/webengineaccesskey.h
/usr/include/KF5/webengineviewer/webengineexporthtmlpagejob.h
/usr/include/KF5/webengineviewer/webengineexportpdfpagejob.h
/usr/include/KF5/webengineviewer/webenginemanagescript.h
/usr/include/KF5/webengineviewer/webenginepage.h
/usr/include/KF5/webengineviewer/webenginescript.h
/usr/include/KF5/webengineviewer/webengineview.h
/usr/include/KF5/webengineviewer/webengineviewer_export.h
/usr/include/KF5/webengineviewer/webhittest.h
/usr/include/KF5/webengineviewer/webhittestresult.h
/usr/include/KF5/webengineviewer/zoomactionmenu.h
/usr/include/KF5/webengineviewer_version.h
/usr/lib64/cmake/KF5MessageComposer/KF5MessageComposerConfig.cmake
/usr/lib64/cmake/KF5MessageComposer/KF5MessageComposerConfigVersion.cmake
/usr/lib64/cmake/KF5MessageComposer/KF5MessageComposerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MessageComposer/KF5MessageComposerTargets.cmake
/usr/lib64/cmake/KF5MessageCore/KF5MessageCoreConfig.cmake
/usr/lib64/cmake/KF5MessageCore/KF5MessageCoreConfigVersion.cmake
/usr/lib64/cmake/KF5MessageCore/KF5MessageCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MessageCore/KF5MessageCoreTargets.cmake
/usr/lib64/cmake/KF5MessageList/KF5MessageListConfig.cmake
/usr/lib64/cmake/KF5MessageList/KF5MessageListConfigVersion.cmake
/usr/lib64/cmake/KF5MessageList/KF5MessageListTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MessageList/KF5MessageListTargets.cmake
/usr/lib64/cmake/KF5MessageViewer/KF5MessageViewerConfig.cmake
/usr/lib64/cmake/KF5MessageViewer/KF5MessageViewerConfigVersion.cmake
/usr/lib64/cmake/KF5MessageViewer/KF5MessageViewerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MessageViewer/KF5MessageViewerTargets.cmake
/usr/lib64/cmake/KF5MimeTreeParser/KF5MimeTreeParserConfig.cmake
/usr/lib64/cmake/KF5MimeTreeParser/KF5MimeTreeParserConfigVersion.cmake
/usr/lib64/cmake/KF5MimeTreeParser/KF5MimeTreeParserTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MimeTreeParser/KF5MimeTreeParserTargets.cmake
/usr/lib64/cmake/KF5TemplateParser/KF5TemplateParserConfig.cmake
/usr/lib64/cmake/KF5TemplateParser/KF5TemplateParserConfigVersion.cmake
/usr/lib64/cmake/KF5TemplateParser/KF5TemplateParserTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TemplateParser/KF5TemplateParserTargets.cmake
/usr/lib64/cmake/KF5WebEngineViewer/KF5WebEngineViewerConfig.cmake
/usr/lib64/cmake/KF5WebEngineViewer/KF5WebEngineViewerConfigVersion.cmake
/usr/lib64/cmake/KF5WebEngineViewer/KF5WebEngineViewerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5WebEngineViewer/KF5WebEngineViewerTargets.cmake
/usr/lib64/libKF5MessageComposer.so
/usr/lib64/libKF5MessageCore.so
/usr/lib64/libKF5MessageList.so
/usr/lib64/libKF5MessageViewer.so
/usr/lib64/libKF5MimeTreeParser.so
/usr/lib64/libKF5TemplateParser.so
/usr/lib64/libKF5WebEngineViewer.so
/usr/lib64/qt5/mkspecs/modules/qt_MessageComposer.pri
/usr/lib64/qt5/mkspecs/modules/qt_MessageCore.pri
/usr/lib64/qt5/mkspecs/modules/qt_MessageList.pri
/usr/lib64/qt5/mkspecs/modules/qt_MessageViewer.pri
/usr/lib64/qt5/mkspecs/modules/qt_TemplateParser.pri
/usr/lib64/qt5/mkspecs/modules/qt_WebEngineViewer.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5MessageComposer.so.5
/usr/lib64/libKF5MessageComposer.so.5.14.2
/usr/lib64/libKF5MessageCore.so.5
/usr/lib64/libKF5MessageCore.so.5.14.2
/usr/lib64/libKF5MessageList.so.5
/usr/lib64/libKF5MessageList.so.5.14.2
/usr/lib64/libKF5MessageViewer.so.5
/usr/lib64/libKF5MessageViewer.so.5.14.2
/usr/lib64/libKF5MimeTreeParser.so.5
/usr/lib64/libKF5MimeTreeParser.so.5.14.2
/usr/lib64/libKF5TemplateParser.so.5
/usr/lib64/libKF5TemplateParser.so.5.14.2
/usr/lib64/libKF5WebEngineViewer.so.5
/usr/lib64/libKF5WebEngineViewer.so.5.14.2
/usr/lib64/qt5/plugins/messageviewer/grantlee/5.0/messageviewer_grantlee_extension.so
/usr/lib64/qt5/plugins/messageviewer/headerstyle/messageviewer_defaultgrantleeheaderstyleplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/messagelib/6a3bf83ab62e047649bdf91a17c9311737cede0f
/usr/share/package-licenses/messagelib/c914b1f9fc73a1ae187da32447bd161823f8b9e8

%files locales -f libmessagecomposer.lang -f libmessagecore.lang -f libmessagelist.lang -f libmessageviewer.lang -f libmimetreeparser.lang -f libtemplateparser.lang -f libwebengineviewer.lang
%defattr(-,root,root,-)

