#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v5
# autospec commit: c02b2fe
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : messagelib
Version  : 24.02.1
Release  : 93
URL      : https://download.kde.org/stable/release-service/24.02.1/src/messagelib-24.02.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.02.1/src/messagelib-24.02.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.02.1/src/messagelib-24.02.1.tar.xz.sig
Summary  : KDE PIM messaging library
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: messagelib-data = %{version}-%{release}
Requires: messagelib-lib = %{version}-%{release}
Requires: messagelib-license = %{version}-%{release}
Requires: messagelib-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : akonadi-search-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : git
BuildRequires : gpgme-dev
BuildRequires : grantlee-dev
BuildRequires : grantleetheme-dev
BuildRequires : kcalendarcore-dev
BuildRequires : kcontacts-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kimap-dev
BuildRequires : kimap-staticdev
BuildRequires : kldap-dev
BuildRequires : kmailtransport-dev
BuildRequires : kmbox-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : ktextaddons-dev
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libgravatar-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : pimcommon-dev
BuildRequires : qca-dev
BuildRequires : qt6base-dev
BuildRequires : qt6webengine-dev
BuildRequires : syntax-highlighting-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
What should be put here?
========================
Stuff here needs to comply with at least these rules (additionally to all the other ones that apply to all code):
- no dependencies on legacy libs (libkdepim)
- no dependencies on:
- libmessagelist
- libmessageviewer
- libmessagecomposer
- used by at least one of the above listed libs
- used by at least one other component (most commonly a second one of the above listed libs)

%package data
Summary: data components for the messagelib package.
Group: Data

%description data
data components for the messagelib package.


%package dev
Summary: dev components for the messagelib package.
Group: Development
Requires: messagelib-lib = %{version}-%{release}
Requires: messagelib-data = %{version}-%{release}
Provides: messagelib-devel = %{version}-%{release}
Requires: messagelib = %{version}-%{release}

%description dev
dev components for the messagelib package.


%package lib
Summary: lib components for the messagelib package.
Group: Libraries
Requires: messagelib-data = %{version}-%{release}
Requires: messagelib-license = %{version}-%{release}

%description lib
lib components for the messagelib package.


%package license
Summary: license components for the messagelib package.
Group: Default

%description license
license components for the messagelib package.


%package locales
Summary: locales components for the messagelib package.
Group: Default

%description locales
locales components for the messagelib package.


%prep
%setup -q -n messagelib-24.02.1
cd %{_builddir}/messagelib-24.02.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711159278
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711159278
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/messagelib
cp %{_builddir}/messagelib-%{version}/.krazy.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/messagelib/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/messagelib-%{version}/LICENSES/BSL-1.0.txt %{buildroot}/usr/share/package-licenses/messagelib/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/messagelib/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/messagelib/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/messagelib/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/messagelib-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/messagelib/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/messagelib/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/messagelib/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/messagelib/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/messagelib/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/messagelib/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/messagelib/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/messagelib/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/messagelib-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/messagelib/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/messagelib-%{version}/messagecomposer/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messagecore/.krazy.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messagecore/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messagelist/.krazy.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messagelist/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messageviewer/.krazy.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/messageviewer/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/mimetreeparser/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/templateparser/.krazy.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/templateparser/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/messagelib-%{version}/webengineviewer/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libmessagelist6
%find_lang libmessageviewer6
%find_lang libmimetreeparser6
%find_lang libmessagecomposer6
%find_lang libmessagecore6
%find_lang libtemplateparser6
%find_lang libwebengineviewer6
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/config.kcfg/customtemplates_kfg.kcfg
/usr/share/config.kcfg/templatesconfiguration_kfg.kcfg
/usr/share/knotifications6/messageviewer.notifyrc
/usr/share/knsrcfiles/messageviewer_header_themes.knsrc
/usr/share/libmessageviewer/pics/enterprise_bottom.png
/usr/share/libmessageviewer/pics/enterprise_bottom_left.png
/usr/share/libmessageviewer/pics/enterprise_bottom_right.png
/usr/share/libmessageviewer/pics/enterprise_icon.png
/usr/share/libmessageviewer/pics/enterprise_left.png
/usr/share/libmessageviewer/pics/enterprise_right.png
/usr/share/libmessageviewer/pics/enterprise_s_left.png
/usr/share/libmessageviewer/pics/enterprise_s_right.png
/usr/share/libmessageviewer/pics/enterprise_sbar.png
/usr/share/libmessageviewer/pics/enterprise_sp_right.png
/usr/share/libmessageviewer/pics/enterprise_sw.png
/usr/share/libmessageviewer/pics/enterprise_top.png
/usr/share/libmessageviewer/pics/enterprise_top_left.png
/usr/share/libmessageviewer/pics/enterprise_top_right.png
/usr/share/libmessageviewer/pics/enterprise_w.png
/usr/share/libmessageviewer/pics/quicklistClosed.png
/usr/share/libmessageviewer/pics/quicklistOpened.png
/usr/share/libmessageviewer/pics/quotecollapse.png
/usr/share/libmessageviewer/pics/quoteexpand.png
/usr/share/messagelist/pics/mail-horizontal-space.png
/usr/share/messagelist/pics/mail-vertical-separator-line.png
/usr/share/messageviewer/about/default/background.png
/usr/share/messageviewer/about/default/main.css
/usr/share/messageviewer/about/default/main.html
/usr/share/messageviewer/about/default/splash.theme
/usr/share/messageviewer/about/default/status.html
/usr/share/messageviewer/defaultthemes/5.2/header.html
/usr/share/messageviewer/defaultthemes/5.2/kmail_default.desktop
/usr/share/messageviewer/defaultthemes/5.2/photo.png
/usr/share/messageviewer/defaultthemes/5.2/photo.svg
/usr/share/messageviewer/defaultthemes/5.2/style.css
/usr/share/messageviewer/longurlServices.json
/usr/share/org.kde.syntax-highlighting/syntax/kmail-template.xml
/usr/share/qlogging-categories6/messagelib.categories
/usr/share/qlogging-categories6/messagelib.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim6/MessageComposer/MessageComposer/AbstractEncryptJob
/usr/include/KPim6/MessageComposer/MessageComposer/AkonadiSender
/usr/include/KPim6/MessageComposer/MessageComposer/AliasesExpandJob
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentClipBoardJob
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentControllerBase
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentFromPublicKeyJob
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentJob
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentModel
/usr/include/KPim6/MessageComposer/MessageComposer/AttachmentVcardFromAddressBookJob
/usr/include/KPim6/MessageComposer/MessageComposer/AutocryptHeadersJob
/usr/include/KPim6/MessageComposer/MessageComposer/AutocryptKeyResolverCore
/usr/include/KPim6/MessageComposer/MessageComposer/Composer
/usr/include/KPim6/MessageComposer/MessageComposer/ComposerAttachmentInterface
/usr/include/KPim6/MessageComposer/MessageComposer/ComposerLineEdit
/usr/include/KPim6/MessageComposer/MessageComposer/ComposerViewBase
/usr/include/KPim6/MessageComposer/MessageComposer/ComposerViewInterface
/usr/include/KPim6/MessageComposer/MessageComposer/ContactPreference
/usr/include/KPim6/MessageComposer/MessageComposer/ContentJobBase
/usr/include/KPim6/MessageComposer/MessageComposer/ConvertSnippetVariableMenu
/usr/include/KPim6/MessageComposer/MessageComposer/ConvertSnippetVariablesJob
/usr/include/KPim6/MessageComposer/MessageComposer/ConvertSnippetVariablesUtil
/usr/include/KPim6/MessageComposer/MessageComposer/DraftStatus
/usr/include/KPim6/MessageComposer/MessageComposer/EditorWatcher
/usr/include/KPim6/MessageComposer/MessageComposer/EncryptJob
/usr/include/KPim6/MessageComposer/MessageComposer/FollowUpReminderSelectDateDialog
/usr/include/KPim6/MessageComposer/MessageComposer/FollowupReminder
/usr/include/KPim6/MessageComposer/MessageComposer/FollowupReminderCreateJob
/usr/include/KPim6/MessageComposer/MessageComposer/GlobalPart
/usr/include/KPim6/MessageComposer/MessageComposer/ImageScalingWidget
/usr/include/KPim6/MessageComposer/MessageComposer/InfoPart
/usr/include/KPim6/MessageComposer/MessageComposer/InsertTextFileJob
/usr/include/KPim6/MessageComposer/MessageComposer/ItipJob
/usr/include/KPim6/MessageComposer/MessageComposer/ItipPart
/usr/include/KPim6/MessageComposer/MessageComposer/JobBase
/usr/include/KPim6/MessageComposer/MessageComposer/KeyResolver
/usr/include/KPim6/MessageComposer/MessageComposer/Kleo_Util
/usr/include/KPim6/MessageComposer/MessageComposer/MDNAdviceDialog
/usr/include/KPim6/MessageComposer/MessageComposer/MDNAdviceHelper
/usr/include/KPim6/MessageComposer/MessageComposer/MDNWarningWidgetJob
/usr/include/KPim6/MessageComposer/MessageComposer/MainTextJob
/usr/include/KPim6/MessageComposer/MessageComposer/MessageComposerSettings
/usr/include/KPim6/MessageComposer/MessageComposer/MessageFactoryNG
/usr/include/KPim6/MessageComposer/MessageComposer/MessageHelper
/usr/include/KPim6/MessageComposer/MessageComposer/MessagePart
/usr/include/KPim6/MessageComposer/MessageComposer/MessageSender
/usr/include/KPim6/MessageComposer/MessageComposer/MultipartJob
/usr/include/KPim6/MessageComposer/MessageComposer/PluginActionType
/usr/include/KPim6/MessageComposer/MessageComposer/PluginComposerInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditor
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorBase
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorCheckBeforeSend
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorCheckBeforeSendInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorCheckBeforeSendManager
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorCheckBeforeSendParams
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConfigureBaseWidget
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConvertText
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConvertTextInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConvertTextManager
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConverterBeforeConvertingData
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorConverterInitialData
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorGrammarCustomToolsViewInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorGrammarManager
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorInit
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorInitInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorInitManager
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorInterface
/usr/include/KPim6/MessageComposer/MessageComposer/PluginEditorManager
/usr/include/KPim6/MessageComposer/MessageComposer/ProtectedHeadersJob
/usr/include/KPim6/MessageComposer/MessageComposer/Recipient
/usr/include/KPim6/MessageComposer/MessageComposer/RecipientLine
/usr/include/KPim6/MessageComposer/MessageComposer/RecipientsEditor
/usr/include/KPim6/MessageComposer/MessageComposer/RichTextComposerNg
/usr/include/KPim6/MessageComposer/MessageComposer/RichTextComposerSignatures
/usr/include/KPim6/MessageComposer/MessageComposer/SaveContactPreferenceJob
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterCreateJob
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterDialog
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterInfo
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterJob
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterRemoveJob
/usr/include/KPim6/MessageComposer/MessageComposer/SendLaterUtil
/usr/include/KPim6/MessageComposer/MessageComposer/SignEncryptJob
/usr/include/KPim6/MessageComposer/MessageComposer/SignJob
/usr/include/KPim6/MessageComposer/MessageComposer/SignatureController
/usr/include/KPim6/MessageComposer/MessageComposer/SinglepartJob
/usr/include/KPim6/MessageComposer/MessageComposer/SkeletonMessageJob
/usr/include/KPim6/MessageComposer/MessageComposer/StatusBarLabelToggledState
/usr/include/KPim6/MessageComposer/MessageComposer/TextPart
/usr/include/KPim6/MessageComposer/MessageComposer/TransparentJob
/usr/include/KPim6/MessageComposer/MessageComposer/Util
/usr/include/KPim6/MessageComposer/messagecomposer/abstractencryptjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/akonadisender.h
/usr/include/KPim6/MessageComposer/messagecomposer/aliasesexpandjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentclipboardjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentcontrollerbase.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentfrompublickeyjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentmodel.h
/usr/include/KPim6/MessageComposer/messagecomposer/attachmentvcardfromaddressbookjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/autocryptheadersjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/autocryptkeyresolvercore.h
/usr/include/KPim6/MessageComposer/messagecomposer/composer.h
/usr/include/KPim6/MessageComposer/messagecomposer/composerattachmentinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/composerlineedit.h
/usr/include/KPim6/MessageComposer/messagecomposer/composerviewbase.h
/usr/include/KPim6/MessageComposer/messagecomposer/composerviewinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/contactpreference.h
/usr/include/KPim6/MessageComposer/messagecomposer/contentjobbase.h
/usr/include/KPim6/MessageComposer/messagecomposer/convertsnippetvariablemenu.h
/usr/include/KPim6/MessageComposer/messagecomposer/convertsnippetvariablesjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/convertsnippetvariablesutil.h
/usr/include/KPim6/MessageComposer/messagecomposer/draftstatus.h
/usr/include/KPim6/MessageComposer/messagecomposer/editorwatcher.h
/usr/include/KPim6/MessageComposer/messagecomposer/encryptjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/followupreminder.h
/usr/include/KPim6/MessageComposer/messagecomposer/followupremindercreatejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/followupreminderselectdatedialog.h
/usr/include/KPim6/MessageComposer/messagecomposer/globalpart.h
/usr/include/KPim6/MessageComposer/messagecomposer/imagescalingwidget.h
/usr/include/KPim6/MessageComposer/messagecomposer/infopart.h
/usr/include/KPim6/MessageComposer/messagecomposer/inserttextfilejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/itipjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/itippart.h
/usr/include/KPim6/MessageComposer/messagecomposer/jobbase.h
/usr/include/KPim6/MessageComposer/messagecomposer/keyresolver.h
/usr/include/KPim6/MessageComposer/messagecomposer/kleo_util.h
/usr/include/KPim6/MessageComposer/messagecomposer/maintextjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/mdnadvicedialog.h
/usr/include/KPim6/MessageComposer/messagecomposer/mdnadvicehelper.h
/usr/include/KPim6/MessageComposer/messagecomposer/mdnwarningwidgetjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagecomposer_debug.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagecomposer_export.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagecomposersettings.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagecomposersettings_base.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagefactoryng.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagehelper.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagepart.h
/usr/include/KPim6/MessageComposer/messagecomposer/messagesender.h
/usr/include/KPim6/MessageComposer/messagecomposer/multipartjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/pluginactiontype.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugincomposerinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditor.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorbase.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorcheckbeforesend.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorcheckbeforesendinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorcheckbeforesendmanager.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorcheckbeforesendparams.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconfigurebasewidget.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconverterbeforeconvertingdata.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconverterinitialdata.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconverttext.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconverttextinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorconverttextmanager.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorgrammarcustomtoolsviewinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorgrammarmanager.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorinit.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorinitinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorinitmanager.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditorinterface.h
/usr/include/KPim6/MessageComposer/messagecomposer/plugineditormanager.h
/usr/include/KPim6/MessageComposer/messagecomposer/protectedheadersjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/recipient.h
/usr/include/KPim6/MessageComposer/messagecomposer/recipientline.h
/usr/include/KPim6/MessageComposer/messagecomposer/recipientseditor.h
/usr/include/KPim6/MessageComposer/messagecomposer/richtextcomposerng.h
/usr/include/KPim6/MessageComposer/messagecomposer/richtextcomposersignatures.h
/usr/include/KPim6/MessageComposer/messagecomposer/savecontactpreferencejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlatercreatejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlaterdialog.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlaterinfo.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlaterjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlaterremovejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/sendlaterutil.h
/usr/include/KPim6/MessageComposer/messagecomposer/signaturecontroller.h
/usr/include/KPim6/MessageComposer/messagecomposer/signencryptjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/signjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/singlepartjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/skeletonmessagejob.h
/usr/include/KPim6/MessageComposer/messagecomposer/statusbarlabeltoggledstate.h
/usr/include/KPim6/MessageComposer/messagecomposer/textpart.h
/usr/include/KPim6/MessageComposer/messagecomposer/transparentjob.h
/usr/include/KPim6/MessageComposer/messagecomposer/util.h
/usr/include/KPim6/MessageComposer/messagecomposer_version.h
/usr/include/KPim6/MessageCore/MessageCore/AttachmentCompressJob
/usr/include/KPim6/MessageCore/MessageCore/AttachmentFromUrlBaseJob
/usr/include/KPim6/MessageCore/MessageCore/AttachmentFromUrlUtils
/usr/include/KPim6/MessageCore/MessageCore/AttachmentLoadJob
/usr/include/KPim6/MessageCore/MessageCore/AttachmentPart
/usr/include/KPim6/MessageCore/MessageCore/AttachmentPropertiesDialog
/usr/include/KPim6/MessageCore/MessageCore/AttachmentUpdateJob
/usr/include/KPim6/MessageCore/MessageCore/AutocryptRecipient
/usr/include/KPim6/MessageCore/MessageCore/AutocryptStorage
/usr/include/KPim6/MessageCore/MessageCore/AutocryptUtils
/usr/include/KPim6/MessageCore/MessageCore/ColorUtil
/usr/include/KPim6/MessageCore/MessageCore/ImageCollector
/usr/include/KPim6/MessageCore/MessageCore/MailingList
/usr/include/KPim6/MessageCore/MessageCore/MessageCoreSettings
/usr/include/KPim6/MessageCore/MessageCore/NodeHelper
/usr/include/KPim6/MessageCore/MessageCore/StringUtil
/usr/include/KPim6/MessageCore/MessageCore/Util
/usr/include/KPim6/MessageCore/messagecore/attachmentcompressjob.h
/usr/include/KPim6/MessageCore/messagecore/attachmentfromurlbasejob.h
/usr/include/KPim6/MessageCore/messagecore/attachmentfromurlutils.h
/usr/include/KPim6/MessageCore/messagecore/attachmentloadjob.h
/usr/include/KPim6/MessageCore/messagecore/attachmentpart.h
/usr/include/KPim6/MessageCore/messagecore/attachmentpropertiesdialog.h
/usr/include/KPim6/MessageCore/messagecore/attachmentupdatejob.h
/usr/include/KPim6/MessageCore/messagecore/autocryptrecipient.h
/usr/include/KPim6/MessageCore/messagecore/autocryptstorage.h
/usr/include/KPim6/MessageCore/messagecore/autocryptutils.h
/usr/include/KPim6/MessageCore/messagecore/colorutil.h
/usr/include/KPim6/MessageCore/messagecore/globalsettings_messagecore.h
/usr/include/KPim6/MessageCore/messagecore/imagecollector.h
/usr/include/KPim6/MessageCore/messagecore/mailinglist.h
/usr/include/KPim6/MessageCore/messagecore/messagecore_export.h
/usr/include/KPim6/MessageCore/messagecore/messagecoresettings.h
/usr/include/KPim6/MessageCore/messagecore/nodehelper.h
/usr/include/KPim6/MessageCore/messagecore/stringutil.h
/usr/include/KPim6/MessageCore/messagecore/util.h
/usr/include/KPim6/MessageCore/messagecore_version.h
/usr/include/KPim6/MessageList/MessageList/AggregationComboBox
/usr/include/KPim6/MessageList/MessageList/AggregationConfigButton
/usr/include/KPim6/MessageList/MessageList/Enums
/usr/include/KPim6/MessageList/MessageList/MessageListUtil
/usr/include/KPim6/MessageList/MessageList/Pane
/usr/include/KPim6/MessageList/MessageList/QuickSearchLine
/usr/include/KPim6/MessageList/MessageList/StorageModel
/usr/include/KPim6/MessageList/MessageList/StorageModelBase
/usr/include/KPim6/MessageList/MessageList/ThemeComboBox
/usr/include/KPim6/MessageList/MessageList/ThemeConfigButton
/usr/include/KPim6/MessageList/MessageList/View
/usr/include/KPim6/MessageList/MessageList/WidgetBase
/usr/include/KPim6/MessageList/messagelist/aggregationcombobox.h
/usr/include/KPim6/MessageList/messagelist/aggregationconfigbutton.h
/usr/include/KPim6/MessageList/messagelist/enums.h
/usr/include/KPim6/MessageList/messagelist/messagelist_export.h
/usr/include/KPim6/MessageList/messagelist/messagelistsettings.h
/usr/include/KPim6/MessageList/messagelist/messagelistutil.h
/usr/include/KPim6/MessageList/messagelist/pane.h
/usr/include/KPim6/MessageList/messagelist/quicksearchline.h
/usr/include/KPim6/MessageList/messagelist/storagemodel.h
/usr/include/KPim6/MessageList/messagelist/storagemodelbase.h
/usr/include/KPim6/MessageList/messagelist/themecombobox.h
/usr/include/KPim6/MessageList/messagelist/themeconfigbutton.h
/usr/include/KPim6/MessageList/messagelist/view.h
/usr/include/KPim6/MessageList/messagelist/widgetbase.h
/usr/include/KPim6/MessageList/messagelist_version.h
/usr/include/KPim6/MessageViewer/MessageViewer/AttachmentStrategy
/usr/include/KPim6/MessageViewer/MessageViewer/BodyPartURLHandler
/usr/include/KPim6/MessageViewer/MessageViewer/BufferedHtmlWriter
/usr/include/KPim6/MessageViewer/MessageViewer/CSSHelper
/usr/include/KPim6/MessageViewer/MessageViewer/CSSHelperBase
/usr/include/KPim6/MessageViewer/MessageViewer/ConfigureWidget
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMCheckPolicy
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMCheckSignatureJob
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMHeaderParser
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMInfo
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMKeyRecord
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManageRulesDialog
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManageRulesWidget
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManager
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManagerAuthenticationServer
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManagerKey
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManagerKeyDialog
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManagerKeyWidget
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMManagerRules
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMRule
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMViewerMenu
/usr/include/KPim6/MessageViewer/MessageViewer/DKIMWidgetInfo
/usr/include/KPim6/MessageViewer/MessageViewer/FileHtmlWriter
/usr/include/KPim6/MessageViewer/MessageViewer/GrantleeHeaderStyle
/usr/include/KPim6/MessageViewer/MessageViewer/GrantleeHeaderTestStyle
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStrategy
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStyle
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStyleInterface
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStyleMenuManager
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStylePlugin
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStylePluginManager
/usr/include/KPim6/MessageViewer/MessageViewer/HeaderStyle_Util
/usr/include/KPim6/MessageViewer/MessageViewer/HtmlBlock
/usr/include/KPim6/MessageViewer/MessageViewer/HtmlWriter
/usr/include/KPim6/MessageViewer/MessageViewer/IconNameCache
/usr/include/KPim6/MessageViewer/MessageViewer/InvitationSettings
/usr/include/KPim6/MessageViewer/MessageViewer/KXFace
/usr/include/KPim6/MessageViewer/MessageViewer/MDNWarningWidget
/usr/include/KPim6/MessageViewer/MessageViewer/MailWebEnginePage
/usr/include/KPim6/MessageViewer/MessageViewer/MailWebEngineView
/usr/include/KPim6/MessageViewer/MessageViewer/MarkMessageReadHandler
/usr/include/KPim6/MessageViewer/MessageViewer/MessagePartRenderPlugin
/usr/include/KPim6/MessageViewer/MessageViewer/MessagePartRendererBase
/usr/include/KPim6/MessageViewer/MessageViewer/MessagePartRendererManager
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerCheckBeforeDeletingInterface
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerCheckBeforeDeletingParameters
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerCheckBeforeDeletingPlugin
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerCheckBeforeDeletingPluginManager
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerCheckBeforeDeletingPluginWidget
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerConfigureSettingsPlugin
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerConfigureSettingsPluginManager
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerConfigureSettingsPluginWidget
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerSettings
/usr/include/KPim6/MessageViewer/MessageViewer/MessageViewerUtil
/usr/include/KPim6/MessageViewer/MessageViewer/MimeType
/usr/include/KPim6/MessageViewer/MessageViewer/ObjectTreeEmptySource
/usr/include/KPim6/MessageViewer/MessageViewer/OpenUrlWithManager
/usr/include/KPim6/MessageViewer/MessageViewer/OpenWithUrlInfo
/usr/include/KPim6/MessageViewer/MessageViewer/PlainHeaderStyle
/usr/include/KPim6/MessageViewer/MessageViewer/PrintMessage
/usr/include/KPim6/MessageViewer/MessageViewer/PrintingSettings
/usr/include/KPim6/MessageViewer/MessageViewer/RemoteContentConfigureDialog
/usr/include/KPim6/MessageViewer/MessageViewer/RemoteContentMenu
/usr/include/KPim6/MessageViewer/MessageViewer/RichHeaderStrategy
/usr/include/KPim6/MessageViewer/MessageViewer/ScamCheckShortUrl
/usr/include/KPim6/MessageViewer/MessageViewer/ScamCheckShortUrlManager
/usr/include/KPim6/MessageViewer/MessageViewer/ScamDetectionInfo
/usr/include/KPim6/MessageViewer/MessageViewer/ScamDetectionWhiteListSettingsManager
/usr/include/KPim6/MessageViewer/MessageViewer/ScamExpandUrlJob
/usr/include/KPim6/MessageViewer/MessageViewer/SpamHeaderAnalyzer
/usr/include/KPim6/MessageViewer/MessageViewer/Stl_Util
/usr/include/KPim6/MessageViewer/MessageViewer/URLHandler
/usr/include/KPim6/MessageViewer/MessageViewer/Viewer
/usr/include/KPim6/MessageViewer/MessageViewer/ViewerPlugin
/usr/include/KPim6/MessageViewer/MessageViewer/ViewerPluginInterface
/usr/include/KPim6/MessageViewer/MessageViewer/ViewerPluginManager
/usr/include/KPim6/MessageViewer/MessageViewer/ViewerPluginToolManager
/usr/include/KPim6/MessageViewer/messageviewer/attachmentstrategy.h
/usr/include/KPim6/MessageViewer/messageviewer/bodyparturlhandler.h
/usr/include/KPim6/MessageViewer/messageviewer/bufferedhtmlwriter.h
/usr/include/KPim6/MessageViewer/messageviewer/configurewidget.h
/usr/include/KPim6/MessageViewer/messageviewer/csshelper.h
/usr/include/KPim6/MessageViewer/messageviewer/csshelperbase.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimcheckpolicy.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimchecksignaturejob.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimheaderparser.h
/usr/include/KPim6/MessageViewer/messageviewer/dkiminfo.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimkeyrecord.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerauthenticationserver.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerkey.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerkeydialog.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerkeywidget.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerrules.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanagerulesdialog.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimmanageruleswidget.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimrule.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimviewermenu.h
/usr/include/KPim6/MessageViewer/messageviewer/dkimwidgetinfo.h
/usr/include/KPim6/MessageViewer/messageviewer/filehtmlwriter.h
/usr/include/KPim6/MessageViewer/messageviewer/globalsettings_messageviewer.h
/usr/include/KPim6/MessageViewer/messageviewer/grantleeheaderstyle.h
/usr/include/KPim6/MessageViewer/messageviewer/grantleeheaderteststyle.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstrategy.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstyle.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstyle_util.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstyleinterface.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstylemenumanager.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstyleplugin.h
/usr/include/KPim6/MessageViewer/messageviewer/headerstylepluginmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/htmlblock.h
/usr/include/KPim6/MessageViewer/messageviewer/htmlwriter.h
/usr/include/KPim6/MessageViewer/messageviewer/iconnamecache.h
/usr/include/KPim6/MessageViewer/messageviewer/invitationsettings.h
/usr/include/KPim6/MessageViewer/messageviewer/kxface.h
/usr/include/KPim6/MessageViewer/messageviewer/mailwebenginepage.h
/usr/include/KPim6/MessageViewer/messageviewer/mailwebengineview.h
/usr/include/KPim6/MessageViewer/messageviewer/markmessagereadhandler.h
/usr/include/KPim6/MessageViewer/messageviewer/mdnwarningwidget.h
/usr/include/KPim6/MessageViewer/messageviewer/messagepartrendererbase.h
/usr/include/KPim6/MessageViewer/messageviewer/messagepartrenderermanager.h
/usr/include/KPim6/MessageViewer/messageviewer/messagepartrenderplugin.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewer_debug.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewer_export.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewercheckbeforedeletinginterface.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewercheckbeforedeletingparameters.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewercheckbeforedeletingplugin.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewercheckbeforedeletingpluginmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewercheckbeforedeletingpluginwidget.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewerconfiguresettingsplugin.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewerconfiguresettingspluginmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewerconfiguresettingspluginwidget.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewersettings.h
/usr/include/KPim6/MessageViewer/messageviewer/messageviewerutil.h
/usr/include/KPim6/MessageViewer/messageviewer/mimetype.h
/usr/include/KPim6/MessageViewer/messageviewer/objecttreeemptysource.h
/usr/include/KPim6/MessageViewer/messageviewer/openurlwithmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/openwithurlinfo.h
/usr/include/KPim6/MessageViewer/messageviewer/plainheaderstyle.h
/usr/include/KPim6/MessageViewer/messageviewer/printingsettings.h
/usr/include/KPim6/MessageViewer/messageviewer/printmessage.h
/usr/include/KPim6/MessageViewer/messageviewer/remotecontentconfiguredialog.h
/usr/include/KPim6/MessageViewer/messageviewer/remotecontentmenu.h
/usr/include/KPim6/MessageViewer/messageviewer/richheaderstrategy.h
/usr/include/KPim6/MessageViewer/messageviewer/scamcheckshorturl.h
/usr/include/KPim6/MessageViewer/messageviewer/scamcheckshorturlmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/scamdetectioninfo.h
/usr/include/KPim6/MessageViewer/messageviewer/scamdetectionwhitelistsettingsmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/scamexpandurljob.h
/usr/include/KPim6/MessageViewer/messageviewer/spamheaderanalyzer.h
/usr/include/KPim6/MessageViewer/messageviewer/stl_util.h
/usr/include/KPim6/MessageViewer/messageviewer/urlhandler.h
/usr/include/KPim6/MessageViewer/messageviewer/viewer.h
/usr/include/KPim6/MessageViewer/messageviewer/viewerplugin.h
/usr/include/KPim6/MessageViewer/messageviewer/viewerplugininterface.h
/usr/include/KPim6/MessageViewer/messageviewer/viewerpluginmanager.h
/usr/include/KPim6/MessageViewer/messageviewer/viewerplugintoolmanager.h
/usr/include/KPim6/MessageViewer/messageviewer_version.h
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/AttachmentTemporaryFilesDirs
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/BodyPart
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/BodyPartFormatter
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/BodyPartFormatterFactory
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/Enums
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/MessagePart
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/NodeHelper
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/ObjectTreeParser
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/ObjectTreeSource
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/PartMetaData
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/PartNodeBodyPart
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/SimpleObjectTreeSource
/usr/include/KPim6/MimeTreeParser/MimeTreeParser/Util
/usr/include/KPim6/MimeTreeParser/mimetreeparser/attachmenttemporaryfilesdirs.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/bodypart.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/bodypartformatter.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/bodypartformatterfactory.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/enums.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/messagepart.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/mimetreeparser_export.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/nodehelper.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/objecttreeparser.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/objecttreesource.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/partmetadata.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/partnodebodypart.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/simpleobjecttreesource.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser/util.h
/usr/include/KPim6/MimeTreeParser/mimetreeparser_version.h
/usr/include/KPim6/TemplateParser/TemplateParser/CustomTemplates
/usr/include/KPim6/TemplateParser/TemplateParser/CustomTemplatesMenu
/usr/include/KPim6/TemplateParser/TemplateParser/DefaultTemplates
/usr/include/KPim6/TemplateParser/TemplateParser/TemplateConvertCommandJob
/usr/include/KPim6/TemplateParser/TemplateParser/TemplateParserEmailAddressRequesterBase
/usr/include/KPim6/TemplateParser/TemplateParser/TemplateParserExtractHtmlInfoResult
/usr/include/KPim6/TemplateParser/TemplateParser/TemplateParserJob
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesCommandMenu
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesConfiguration
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesInsertCommandAction
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesInsertCommandPushButton
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesTextEdit
/usr/include/KPim6/TemplateParser/TemplateParser/TemplatesUtil
/usr/include/KPim6/TemplateParser/templateparser/customtemplates.h
/usr/include/KPim6/TemplateParser/templateparser/customtemplates_kfg.h
/usr/include/KPim6/TemplateParser/templateparser/customtemplatesmenu.h
/usr/include/KPim6/TemplateParser/templateparser/defaulttemplates.h
/usr/include/KPim6/TemplateParser/templateparser/globalsettings_templateparser.h
/usr/include/KPim6/TemplateParser/templateparser/templateconvertcommandjob.h
/usr/include/KPim6/TemplateParser/templateparser/templateparser_export.h
/usr/include/KPim6/TemplateParser/templateparser/templateparseremailaddressrequesterbase.h
/usr/include/KPim6/TemplateParser/templateparser/templateparserextracthtmlinforesult.h
/usr/include/KPim6/TemplateParser/templateparser/templateparserjob.h
/usr/include/KPim6/TemplateParser/templateparser/templatescommandmenu.h
/usr/include/KPim6/TemplateParser/templateparser/templatesconfiguration.h
/usr/include/KPim6/TemplateParser/templateparser/templatesconfiguration_kfg.h
/usr/include/KPim6/TemplateParser/templateparser/templatesinsertcommandaction.h
/usr/include/KPim6/TemplateParser/templateparser/templatesinsertcommandpushbutton.h
/usr/include/KPim6/TemplateParser/templateparser/templatestextedit.h
/usr/include/KPim6/TemplateParser/templateparser/templatesutil.h
/usr/include/KPim6/TemplateParser/templateparser/ui_templatesconfiguration_base.h
/usr/include/KPim6/TemplateParser/templateparser_version.h
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/BlockExternalResourcesUrlInterceptor
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/BlockTrackingUrlInterceptor
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/CheckPhishingUrlCache
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/CheckPhishingUrlJob
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/CheckPhishingUrlUtil
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/CreatePhishingUrlDataBaseJob
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/DeveloperToolDialog
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/FindBarBase
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/FindBarWebEngineView
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/HashCacheManager
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/InterceptorManager
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/LoadExternalReferencesUrlInterceptor
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/LocalDataBaseManager
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/NetworkPluginUrlInterceptor
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/NetworkPluginUrlInterceptorConfigureWidget
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/NetworkPluginUrlInterceptorInterface
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/NetworkUrlInterceptor
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/NetworkUrlInterceptorPluginManager
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/SearchFullHashJob
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/SubmittedFormWarningWidget
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/TrackingWarningWidget
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/UpdateDataBaseInfo
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineAccessKey
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineExportHtmlPageJob
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineExportPdfPageJob
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineManageScript
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEnginePage
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineScript
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebEngineView
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebHitTest
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/WebHitTestResult
/usr/include/KPim6/WebEngineViewer/WebEngineViewer/ZoomActionMenu
/usr/include/KPim6/WebEngineViewer/webengineviewer/blockexternalresourcesurlinterceptor.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/blocktrackingurlinterceptor.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/checkphishingurlcache.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/checkphishingurljob.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/checkphishingurlutil.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/createphishingurldatabasejob.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/developertooldialog.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/findbarbase.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/findbarwebengineview.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/hashcachemanager.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/interceptormanager.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/loadexternalreferencesurlinterceptor.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/localdatabasemanager.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/networkpluginurlinterceptor.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/networkpluginurlinterceptorconfigurewidget.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/networkpluginurlinterceptorinterface.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/networkurlinterceptor.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/networkurlinterceptorpluginmanager.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/searchfullhashjob.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/submittedformwarningwidget.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/trackingwarningwidget.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/updatedatabaseinfo.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webengineaccesskey.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webengineexporthtmlpagejob.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webengineexportpdfpagejob.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webenginemanagescript.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webenginepage.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webenginescript.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webengineview.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webengineviewer_export.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webhittest.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/webhittestresult.h
/usr/include/KPim6/WebEngineViewer/webengineviewer/zoomactionmenu.h
/usr/include/KPim6/WebEngineViewer/webengineviewer_version.h
/usr/lib64/cmake/KPim6MessageComposer/KPim6MessageComposerConfig.cmake
/usr/lib64/cmake/KPim6MessageComposer/KPim6MessageComposerConfigVersion.cmake
/usr/lib64/cmake/KPim6MessageComposer/KPim6MessageComposerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MessageComposer/KPim6MessageComposerTargets.cmake
/usr/lib64/cmake/KPim6MessageCore/KPim6MessageCoreConfig.cmake
/usr/lib64/cmake/KPim6MessageCore/KPim6MessageCoreConfigVersion.cmake
/usr/lib64/cmake/KPim6MessageCore/KPim6MessageCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MessageCore/KPim6MessageCoreTargets.cmake
/usr/lib64/cmake/KPim6MessageList/KPim6MessageListConfig.cmake
/usr/lib64/cmake/KPim6MessageList/KPim6MessageListConfigVersion.cmake
/usr/lib64/cmake/KPim6MessageList/KPim6MessageListTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MessageList/KPim6MessageListTargets.cmake
/usr/lib64/cmake/KPim6MessageViewer/KPim6MessageViewerConfig.cmake
/usr/lib64/cmake/KPim6MessageViewer/KPim6MessageViewerConfigVersion.cmake
/usr/lib64/cmake/KPim6MessageViewer/KPim6MessageViewerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MessageViewer/KPim6MessageViewerTargets.cmake
/usr/lib64/cmake/KPim6MimeTreeParser/KPim6MimeTreeParserConfig.cmake
/usr/lib64/cmake/KPim6MimeTreeParser/KPim6MimeTreeParserConfigVersion.cmake
/usr/lib64/cmake/KPim6MimeTreeParser/KPim6MimeTreeParserTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6MimeTreeParser/KPim6MimeTreeParserTargets.cmake
/usr/lib64/cmake/KPim6TemplateParser/KPim6TemplateParserConfig.cmake
/usr/lib64/cmake/KPim6TemplateParser/KPim6TemplateParserConfigVersion.cmake
/usr/lib64/cmake/KPim6TemplateParser/KPim6TemplateParserTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6TemplateParser/KPim6TemplateParserTargets.cmake
/usr/lib64/cmake/KPim6WebEngineViewer/KPim6WebEngineViewerConfig.cmake
/usr/lib64/cmake/KPim6WebEngineViewer/KPim6WebEngineViewerConfigVersion.cmake
/usr/lib64/cmake/KPim6WebEngineViewer/KPim6WebEngineViewerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6WebEngineViewer/KPim6WebEngineViewerTargets.cmake
/usr/lib64/libKPim6MessageComposer.so
/usr/lib64/libKPim6MessageCore.so
/usr/lib64/libKPim6MessageList.so
/usr/lib64/libKPim6MessageViewer.so
/usr/lib64/libKPim6MimeTreeParser.so
/usr/lib64/libKPim6TemplateParser.so
/usr/lib64/libKPim6WebEngineViewer.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKPim6MessageComposer.so.6.0.1
/V3/usr/lib64/libKPim6MessageCore.so.6.0.1
/V3/usr/lib64/libKPim6MessageList.so.6.0.1
/V3/usr/lib64/libKPim6MessageViewer.so.6.0.1
/V3/usr/lib64/libKPim6MimeTreeParser.so.6.0.1
/V3/usr/lib64/libKPim6TemplateParser.so.6.0.1
/V3/usr/lib64/libKPim6WebEngineViewer.so.6.0.1
/V3/usr/lib64/qt6/plugins/pim6/messageviewer/headerstyle/messageviewer_defaultgrantleeheaderstyleplugin.so
/V3/usr/lib64/qt6/plugins/pim6/messageviewer/kf6/ktexttemplate/messageviewer_ktexttemplate_extension.so
/usr/lib64/libKPim6MessageComposer.so.6
/usr/lib64/libKPim6MessageComposer.so.6.0.1
/usr/lib64/libKPim6MessageCore.so.6
/usr/lib64/libKPim6MessageCore.so.6.0.1
/usr/lib64/libKPim6MessageList.so.6
/usr/lib64/libKPim6MessageList.so.6.0.1
/usr/lib64/libKPim6MessageViewer.so.6
/usr/lib64/libKPim6MessageViewer.so.6.0.1
/usr/lib64/libKPim6MimeTreeParser.so.6
/usr/lib64/libKPim6MimeTreeParser.so.6.0.1
/usr/lib64/libKPim6TemplateParser.so.6
/usr/lib64/libKPim6TemplateParser.so.6.0.1
/usr/lib64/libKPim6WebEngineViewer.so.6
/usr/lib64/libKPim6WebEngineViewer.so.6.0.1
/usr/lib64/qt6/plugins/pim6/messageviewer/headerstyle/messageviewer_defaultgrantleeheaderstyleplugin.so
/usr/lib64/qt6/plugins/pim6/messageviewer/kf6/ktexttemplate/messageviewer_ktexttemplate_extension.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/messagelib/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/messagelib/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/messagelib/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/messagelib/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/messagelib/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/messagelib/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/messagelib/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/messagelib/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/messagelib/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/messagelib/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/messagelib/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/messagelib/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libmessagelist6.lang -f libmessageviewer6.lang -f libmimetreeparser6.lang -f libmessagecomposer6.lang -f libmessagecore6.lang -f libtemplateparser6.lang -f libwebengineviewer6.lang
%defattr(-,root,root,-)

